### ISSUE TITLE
mzid 1.2 to do list from Gent

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/mzIdentML#1]
Hi all,

Various items from the sessions this morning in Gent:

- [ ]  mzid 1.2 validator not easy to locate on GitHub - @germa , are you able to make this prominently available as a build under a "Downloads" webpage on Githut. Apparently, it is fairly easy to build end user web-pages on GitHub - @Tobias and @ypriverol has experience of this.

 - [ ] There are various bugs in the validator - if you have identified one, please make sure to email it to @germa to fix
 
 - [ ]  @edeutsch has taken an action item to do some CV tidying, particularly around scores for PSMs, 
   PTM, peptides, proteins and protein groups

  - [x] We need ~11 new CV terms, as detailed in Table 2 of the spec doc (just pushed to GitHub) for combined spectra as input to searches

  - [x] Term MS:102499 peptide level score should be deprecated as this was never intended to go in the CV - @germa , can you do this please

  - [x] Terms starting "group PSMs by..." are under the wrong parent. They should be under a new parent 
    term called "identification parameters", and a new link added to the mapping file for 
    "AdditionalSearchParameters" allowing the child terms of this term to be used i.e. these terms are 
    intended to be used in this part of the Protocol.

  - [x]  These terms: de novo, proteogenomics spectral  need an extra parent term: special processing (MS:1002489), so they trigger special behaviour of the validator.

Please add to this list with things I missed,
best wishes
@andrewrobertjones

**Comment by germa** [comment]
Done all CV stuff and added README.md file with a download link for the validator

**Comment by andrewrobertjones** [comment]
All moved to other issues or done, closing
