### ISSUE TITLE
Scientific notation not allowed in PTM localization scores?

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#10]
Why is the following not allowed?

"MS:1001969" name="phosphoRS score" value="1:1.0468246849444967E-8:4:false"

Is scientific annotation not supported?

Full error:
"The regular expression in SpectrumIdentificationItem (id='SII_4070_1') element at /MzIdentML/DataCollection/AnalysisData/SpectrumIdentificationList/SpectrumIdentificationResult/SpectrumIdentificationItem/cvParam ('phosphoRS score') is not valid."

**Comment by germa** [comment]
Resolved
