### ISSUE TITLE
Peptide <-> PeptideEvidence relationship - is this valid?

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/mzIdentML#102]
Hi,

my example refers to file /examples/1_2examples/crosslinking/xiFDR-CrossLinkExample.mzid, 
which is currently passed by the validator.

If you search for the peptide with id "54604449_54604449_6_6_p0",
then it seems to be missing any associated PeptideEvidence element.

Also, if you then go to its occurrence within a SpectrumIdentification (SII_3312_2),
then search for the peptideEvidence_ref of the PeptideEvidenceRef within that identification ("pepevid_psm252621340_pep54604449_protP02768-A_decoy_576"),
then check the peptide_ref of that PeptideEvidence,
it is "54604449_54604449_6_6_p**1**",
i.e. its not the one we started with.

Assuming I'm not making some mistake, some questions:
- is it valid that "54604449_54604449_6_6_p0" has no associated PeptideEvidence whilst most of the peptides in the file do?
- is it valid that a SpectrumIdentification can contain a PeptideEvidenceRef element where the peptide_ref of the corresponding PeptideEvidence is not the peptide_ref the SpectrumIdentification identifies?

I can't find anything in the specification document that's explicit about these questions. Both feel wrong to me, especially the second.

If these aren't valid then could the validator be made to detect these errors? 

If they're not valid and there's nothing in the documentation about it, then could the documentation be made clearer on these points?

As an aside, aren't the PeptideEvidenceRef elements redundant if the relation between Peptides and PeptideEvidences is properly enforced? i.e. you only need the id of the peptide and you can get the associated PeptideEvidences from that?

best wishes,
Colin

**Comment by germa** [comment]
Hi Colin,

yes I too think that both cases should not occurs. I'll add a check for this in the validator.

Cheers,
Gerhard

**Comment by colin-combe** [comment]
OK, thanks for looking at this,
Colin

**Comment by germa** [comment]
added checks in version mzIdentMLValidator_GUI_v1.4.32-SNAPSHOT
