### ISSUE TITLE
validator check for start and end att's of PeptideEvidence

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/mzIdentML#103]
Hi,
this came up in this context - https://groups.google.com/forum/#!topic/simxl/UOqJp8NK-70

Could the validator require the start and end attributes of PeptideEvidences to be present if the SearchType is not  MS:1001010 (de novo search)? I think this would be in line with the specification (6.49)?

Also, it seems like SIM-XL's mzIdentML output should be included as an example of cross-linking data? It passes validation, I'll make a pull request to encourage including it :)

best wishes,
Colin

(@diogobor)

**Comment by germa** [comment]
Solved in mzIdentMLValidator_GUI_v1.4.31-SNAPSHOT

**Comment by colin-combe** [comment]
Thanks!
