### ISSUE TITLE
Validator passes four MS:1002511 with the same 'value' within single SIR? [EDIT - this is correct]

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/mzIdentML#105]
I think the fix for #100 changed the validator from failing valid files to passing invalid files? 

I think the validator is now passing files where there are 4 SpectrumIdentificationItems containing an MS:1002511 cv param with the same value within a single SpectrumIdentificationResult.

So the problem's still there. Can't reopen the closed issue so making new one.

**Comment by colin-combe** [comment]
OK... something I wasn't aware of from the specification:
"In the case, of “light” and “heavy” cross-linked peptides, there SHOULD
be exactly four <SpectrumIdentificationItem> elements, all sharing the same identifier under “cross-link spectrum
identification item”"

So, wrong when wrote the title to this issue. 

But i'm still not sure about the code here https://github.com/HUPO-PSI/mzIdentML/blob/e998231868d613c723705ed9f649959cdcedd296/validator/trunk/src/main/java/psidev/psi/pi/validator/objectrules/XLinkSIIObjectRule.java#L138

Aren't 2 and 4 the only valid number of MS:1002511 with the same 'value' within single SIR?

I still feel like this check is taking place within the wrong scope (SpectrumIdentificationList rather SpectrumIdentificationResult) as I think this is what was happening before with regards #100 

I'm going to try and check

**Comment by colin-combe** [comment]
I can't test what's happening because I'm struggling to build the validator.

Maven is complaining: The following artifacts could not be resolved: psidev.psi.tools:validator:jar:2.0.7, uk.ac.ebi.jmzidml:jmzidentml:jar:1.1.9, psidev.psi.tools:xxindex:jar:0.14:

Could easily be another error by me.

**Comment by germa** [comment]
adapted in version mzIdentMLValidator_GUI_v1.4.32-SNAPSHOT (see also issue #100)
