### ISSUE TITLE
validator gives different results second time its run

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/mzIdentML#106]
this seemed a bit mysterious to me...
using validator v1.4.30 to validate the file in pull request #104,
it fails because XLMOD now needs to be lower case.

However, if I click the Validate button a second time I get different results. 

The following error is missing second time round:
Message 2:
    Rule ID: PeptideModification_must_rule
    Level: ERROR
    Context(/modification/cvParam/@accession ) in 115 locations
    --> The result found at: /modification/cvParam/@accession for which the values is  ''XLMOD:01002'' didn't match any of the 8 specified CV terms:

**Comment by andrewrobertjones** [comment]
Hi Colin,

Did you ever get these resolved? I haven't been following these issues for a while, so apologies that some have fallen down the cracks.
cheers
Andy

**Comment by germa** [comment]
Solved in mzIdentMLValidator_GUI_v1.4.31-SNAPSHOT
