### ISSUE TITLE
SoftwareName cannot be valid with "custom unreleased software"

### ISSUE THREAD

**Issue by mobiusklein** [HUPO-PSI/mzIdentML#107]
The `SoftwareName` element the specification must contain a single parameter that names a term descended from `analysis software`, which makes it impossible to generate a semantically valid document if the software used does not have an entry in the controlled vocabulary.

The natural term to use when describing unreleased software is MS:1000799, "custom unreleased software tool", but it is only classified as `software`, and therefore does not satisfy the the semantic validator.

Is there a reason MS:10007999 is not valid here?

Additionally, the specification documentation for `SoftwareName` states it requires a minimum of 1 and a maximum of 1 `cvParam` and a minimum of 1 and a maximum of 1 `userParam`, which isn't consistent with reality. It either means you must provide both, or the authors intended it to mean you must provide either one or the other, but providing a `userParam` here would make this element hard to use.

**Comment by andrewrobertjones** [comment]
hi Joshua,

In terms of the first point, you can get a software name added to the CV fairly easily, even if the software is not released yet, please just email a request to psidev-ms-vocab@lists.sourceforge.net, or put your request here and we will handle it.

In terms of the second point, it looks like this is an artefact of how the spec doc was generated, it should be an 1:1 cvParam or userParam.

In ter

**Comment by mobiusklein** [comment]
In that case, would using a userParam in `<SoftwareName>` be semantically valid?

To register a new term, beyond the term's name and definition, and perhaps a DOI, what else do I need to provide? I'm actually working with data produced by a tool that was published, but not by me, so I don't know the etiquette for registering terms for other peoples' work.

**Comment by germa** [comment]
Hi Joshua,

even the software is not from you, you can request at  psidev-ms-vocab@lists.sourceforge.net a term for it to be included in CV.

**Comment by mobiusklein** [comment]
If the semantics of the `<SoftwareName>` are working as intended, then I think this issue has been closed. The CV terms I submitted have been added via the mailing list.
