### ISSUE TITLE
Spec doc problem on SearchDatabase

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzIdentML#108]
As spotted by Andrew C and Gerhard, there are a few issues (mostly in the spec doc) relating to SearchDatabase and its cvParams, which need to be resolved. We should put out a minor update on the spec doc and make the change in the mapping file

I think there are 3 problems here:

1) The "Example cvParams" given in the specification document for <DatabaseName> are wrong,
  since they should be cvParams for <SearchDatabase>:
  <cvParam accession="MS:1001197" cvRef="PSI-MS" name="DB composition target+decoy"/>
  <cvParam accession="MS:1001283" cvRef="PSI-MS" value="^XXX" name="decoy DB accession regexp"/>
  <cvParam accession="MS:1001195" cvRef="PSI-MS" name="decoy DB type reverse"/>
  <cvParam accession="MS:1001073" cvRef="PSI-MS" name="database type amino acid"/>

2) in the specification document for <DatabaseName> it should be:
  Path /MzIdentML/DataCollection/Inputs/SearchDatabase/DatabaseName
  MAY supply a *child* term of MS:1001013 (database name) one time
instead of
  MAY supply a *child* term of MS:1001013 (database name) one or more times
because according to the schema definition we allow only one userParam or cvParam here

3) the mapping rule for <DatabaseName> is wrong (isRepeatable should be false):
    <CvMappingRule id="SearchDatabaseDatabaseName_may_rule" cvElementPath="/MzIdentML/DataCollection/Inputs/searchDatabase/databaseName/cvParam/@accession" requirementLevel="MAY" scopePath="/MzIdentML/DataCollection/Inputs/searchDatabase/databaseName" cvTermsCombinationLogic="OR">
        <CvTerm termAccession="MS:1001013" useTermName="false" useTerm="false" termName="database name" isRepeatable="true" allowChildren="true" cvIdentifierRef="MS" />
    </CvMappingRule>
should be 
    <CvMappingRule id="SearchDatabaseDatabaseName_may_rule" cvElementPath="/MzIdentML/DataCollection/Inputs/searchDatabase/databaseName/cvParam/@accession" requirementLevel="MAY" scopePath="/MzIdentML/DataCollection/Inputs/searchDatabase/databaseName" cvTermsCombinationLogic="OR">
        <CvTerm termAccession="MS:1001013" useTermName="false" useTerm="false" termName="database name" isRepeatable="false" allowChildren="true" cvIdentifierRef="MS" />
    </CvMappingRule>
Best wishes,
Gerhard 

Am 05.09.2018 um 16:13 schrieb Jones, Andy:
 
<SearchDatabase numDatabaseSequences="40400" location="C:\Users\hba041\My_Git_Applications\peptide-shaker.wiki\data\2016_04_05\uniprot-human-reviewed-trypsin-april-2016_concatenated_target_decoy.fasta" id="SearchDB_1">
<FileFormat>
<cvParam cvRef="PSI-MS" accession="MS:1001348" name="FASTA format"/>
</FileFormat>
<DatabaseName>
<userParam name="uniprot-human-reviewed-trypsin-april-2016_concatenated_target_decoy.fasta"/>
</DatabaseName>
     <cvParam accession="MS:1001283" cvRef="PSI-MS" value="DECOY" 
name="decoy DB accession regexp"/>
     <cvParam accession="MS:1001195" cvRef="PSI-MS" name="decoy DB type reverse"/>
     <cvParam accession="MS:1001073" cvRef="PSI-MS" name="database type amino acid"/> 
</SearchDatabase>

**Comment by germa** [comment]
isRepeatable in the mapping rule SearchDatabaseDatabaseName_may_rule is now set to false

**Comment by germa** [comment]
spec doc updated
