### ISSUE TITLE
Incorrect CV term requirement for PTM localization scoring?

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#11]
It seems to be mandatory to add MS:1002507 (modification rescoring:false localization rate) (or any of its child terms, of which there are none btw) when including MS:1002491 (modification localization scoring) in the AdditionalSearchParams list.

This means that terms such as MS:1001969 (phosphoRS score), MS:1002536 (D-Score), MS:1002550 (peptide:phosphoRS score and MS:1002553 (peptide:D-Score) (and others) cannot be used for the PTM rescoring.

I think that either these terms have to be children of MS:1002507 (modification rescoring:false localization rate) or the mandatory term when using modification rescoring ought to be MS:1002505 (regular expression for modification localization scoring) or one of its children?

**Comment by germa** [comment]
Resolved.
