### ISSUE TITLE
Update list of anticipated CV terms during validation

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#12]
The following terms ought to be anticipated when running the validator (and thus remove the warning messages):

- MS:1002567 (phosphoRS score threshold) and MS:1002557 (D-Score threshold) ought to be anticipated terms under Threshold under SpectrumIdentificationProtocol?

- MS:1002497 (group PSMs by sequence with modifications) (and the other new related terms) ought to be anticipated terms under AdditionalSearchParams?

- MS:1000894 (retention time) ought to be anticipated terms under SpectrumIdentificationResult?

- MS:1002471, MS:1002470 and MS:1002542 ought to be anticipated terms under ProteinAmbiguityGroup?

**Comment by germa** [comment]
Resolved.
