### ISSUE TITLE
how to recompile Validator?

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/mzIdentML#126]
Hi,

I've tried to rebuild the Validator (using Netbeans as the repository already contained project files for this IDE).

It failed with the following error:

```
Failed to execute goal on project mzIdentMLValidator: 
Could not resolve dependencies for project psidev.psi.pi:mzIdentMLValidator:jar:1.4.35-SNAPSHOT: 
Failed to collect dependencies at psidev.psi.tools:validator:jar:2.0.10 
-> psidev.psi.tools:ontology-manager:jar:2.0.10 
-> uk.ac.ebi.ols:ols-core:jar:1.19 
-> proteomics:proteomics-common:jar:1.5: 
Failed to read artifact descriptor for proteomics:proteomics-common:jar:1.5: 
Could not transfer artifact proteomics:proteomics-common:pom:1.5 from/to maven-default-http-blocker (http://0.0.0.0/): 

Blocked mirror for repositories: 
[
nexus-ebi-repo-old (http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/, default, releases+snapshots), 
nexus-ebi-release-repo (http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/, default, releases+snapshots), 
nexus-ebi-snapshot-repo (http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-snapshots/, default, releases+snapshots), 
ebi-repo (http://www.ebi.ac.uk/~maven/m2repo, default, releases+snapshots), 
ibiblio-repo (http://mirrors.ibiblio.org/pub/mirrors/maven2/, default, releases+snapshots), 
java-repo (http://download.java.net/maven/2/, default, releases+snapshots)
] 
-> [Help 1]
```
I'm not sure how to interpret this? Are some of the dependencies missing or only accessible when inside EBI?

Can anyone give advice on how to make it compile?
Thanks,
Colin

**Comment by javizca** [comment]
Sorry, I forgot to reply to this. I think Gerhard Mayer was the last person working in the mzidentML validator. I think the EBI maven repository also had to change. I can investigate this a bit further

**Comment by javizca** [comment]
I was discussing this with @ypriverol yesterday. We have not really touched the validator for a very long time. There is some substantial work that would be needed to "revitalise" it. We can discuss the priorities and timeframe in a future call or in our kickoff meeting on November.

**Comment by edeutsch** [comment]
I think @mobiusklein put some effort into revitalizing it but I don't know with that degree of success. But maybe he could comment.

**Comment by mobiusklein** [comment]
I hit the same wall that Colin did, being unable to locate certain dependencies via the package registry and not being able to locate those libraries' source code to work around the registry.

**Comment by ypriverol** [comment]
I will try to solve the dependency issues today.

**Comment by colin-combe** [comment]
Awesome - thanks,
Colin

**Comment by ypriverol** [comment]
Hi @colin-combe, I have created a new clean repo here https://github.com/ypriverol/mzidentml-validator. The project is Java 1.8-based, and you should be able to build it, all dependencies issues have been solved. Please take a look to it. I will close this issue. If you have any problems please open a new one.
