### ISSUE TITLE
SearchModification MAY supply a *child* term of MS:1001471 (peptide modification details) only once?

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/mzIdentML#127]
in the definition of SearchModification on p.65 of the spec it says "MAY supply a *child* term of MS:1001471 (peptide modification details) only once". 
Is that correct? E.g. a fragment may have multiple neutral losses.

> In case it helps, Mascot supports multiple neutral losses for variable modifications, but we don't currently print MS:1001524 for SearchModification (only Peptide/Modification). You could argue it should be able to specify all NLs that were part of the search space, which means you would want more than one child of MS:1001471. Mascot currently doesn't support neutral losses at crosslinked sites, so it doesn't make a difference for mzIdentML 1.2.1 support.

**Comment by vrkosk** [comment]
If Mascot is the only search engine that supports multiple neutral losses, this issue is not a blocker for mzIdentML 1.2.1.
