### ISSUE TITLE
file format for extension documents?

### ISSUE THREAD

**Issue by colin-combe** [HUPO-PSI/mzIdentML#129]
the [new version of the spec](https://github.com/HUPO-PSI/mzIdentML/blob/master/specification_document/specdoc1_2/mzIdentML1.2.1-draft.docx) will refer to extension documents that describe additional features.

What file format do we want to use for these documents? Its been suggested to move away from .docx  "to ASCIIDoctor format (to match mzTab) or failing that an enhanced Markdown". Something more text based that makes tracking changes in GH easier might be better than .docx

**Comment by javizca** [comment]
Nils Hoffmann is the person to ask about this, although we need to take a joint decision about how to proceed. I don't have any experience in using the ASCIIDoctor format

**Comment by colin-combe** [comment]
whats missing from 'normal' markdown that we might need? (@mobiusklein)

**Comment by colin-combe** [comment]
how do we contact Nils Hoffman?

**Comment by colin-combe** [comment]
discussed the file format for specification documents with @nilshoffmann.

Asciidoc has many advantages (github can render it, can properly track changes via git) compared to what we're currently doing with .docx files.

we will use asciidoc for the crosslinking extension document (possibly also other extension documents @mobiusklein ?)  and potentially also move the main specification document to Asciidoc ( @javizca , @andrewrobertjones )

This will match what has been done with the mzTab specification.
