### ISSUE TITLE
Cross-link site specificity might need refinement

### ISSUE THREAD

**Issue by timosachsenberg** [HUPO-PSI/mzIdentML#13]
Hi,
I wanted to point out that the current format e.g. "(K,L,n-term)" might be insufficient to represent site-specific and site-unspecific terminal cross-linker.
e.g. in unimod there is the distinction between a terminal modification e.g. ("N-term") and a terminal modification at a specific site e.g. ("N-term K").
Maybe we could also adapt this notation.

**Comment by mwalzer** [comment]
definitely something the chem. experts should consider during their offline discussions on the linker definitions list, see https://github.com/HUPO-PSI/mzIdentML/blob/master/cv/XLMOD.csv

**Comment by lutzfischer** [comment]
I agree that this would make sense. Hoever at the moment we don't have a cross-linker of type "N-term K" or equivalent.
Currently used are:
* Amino-Acids - signifies that the cross-linker reacts with these amino-acids
* N-term/C-term - refers to N-terminal or C-terminal end of the protein

If we want to specify now how things will be treated even if we don't have examples of them then we need a separate document to keep these information.

One more related question would be whether it make sense to distinguish protein and peptide terminal. This probably only meaning full if looking at natural occurring cross-links e.g. Ubiguitilation - not sure if there are any natural occurring peptide  C-/N-terminal cross-links.

**Comment by timosachsenberg** [comment]
Ok thanks for the comment. 

Maybe it's not really relevant at this point but I give some information how it is done in unimod.

If we decide to be consistent with the naming scheme in unimod, we could use:
"Protein N-term" or "Protein C-term" for protein terminal cross-linker
"N-term" or "C-term" for peptide terminal cross-linker (probably less relevant as you pointed out)
(or the empty string for non-terminal ones)
and then add the residue (if it is site specific cross-linker):

What I currently did not understand (sorry I did not make it to the calls) how the pairs are specified. Is it possible to say (and does it make sense?), e.g. the cross-linker can link K and Y, but not K and K or Y and Y? How would this definition differ from a cross-linker that can link e.g. K and K, too?

If we need to express something like this (sorry again if this has already been discussed) is this already possible using the encoding in the column?

I am asking, because as I understand it, the & currently stands for the cross-product of the two sets (=all combinations pairs between the left side and the right side). 

If we want to support the general case this could be easily extended.

**Comment by lutzfischer** [comment]
Ok first point - terminal cross-links: One reason I did not want to put Protein-C/N-term in is that basically for all non-natural cross-linkers that distinction depends on when you add the cross-linker - e.g. before or after digest. So it's not an inherent feature of the cross-linker. Admittedly there are probably not many experiments that would do cross-linking after a digest...

But I guess we could change to Protein N-Term to keep in line with uniprot. Does anybody else here have an opinion on it?

So we could define a cross-linker that links Protein-N-terminal methionine or KSTY anywhere else  to anything as : 
(N-Term M,K,S,T,Y)&(*)
or
(Protein N-Term M,K,S,T,Y)&(*)
For the uniprot-version.
What ever cross-linker that would be...

Point two : Yes the ampersand means that the cross-linker can link anything from the left side with anything  on the right side but not within the left or the right. E.g. for EDC:
(K,S,T,Y,n-term)&(E,D,c-term)
means 
it links K or S or T or Y or the n-terminal to either E or D or the C-terminal but not K to S or E to D.
Compared to BS3:
(K,S,T,Y,N-term)&(K,S,T,Y,N-term)
- can link any K,S,T,Y or N-Term to any K,S,T,Y or N-Term
e.g K to K, K to S, K to T, K to Y, K to N-term, S to K, S to S ... 

I am not sure if I understand your example right but would that not have been already covered?
Linking K to Y only:
(K)&(Y)
Linking K to K or Y
(K)&(K,Y)
Linking K to K
(K)&(K)

**Comment by timosachsenberg** [comment]
Thanks for the clarification.
The case we currently (as far as I understood it and mainly from a theoretical point) are not able to represent is e.g.:
Linking K to Y or S to T but at the same time disallowing K to T. I don't know if these cases exist in practice (or might exist in the future - e.g. for special types of zero length cross-linker).

**Comment by sulezinha** [comment]
In that case, for example, is XLMOD-specificity for DSS going to be _(K,S,T,Y,Protein N-term M)&(K,S,T,Y,Protein N-term M)_?

Because, I received one data set from a group and this group also provided me their FASTA file. 
I ran pLink and Kojak to identify spectra for DSS linking. 

Their fasta file has one protein sequence that starts with G. 
Both algorithm gave identification with considering Protein N-term G as linkable, for the validated list.

That fasta file has another protein sequence that starts with M. 
These two algorithms identified both M and also the second residue after M for this protein as linkable, as well.

So, if the specificity checks for DSS considers _Protein N-term M _but _Protein N-term_, such identifications will fail and mzIdentML is not going to consider this identification then, is it? 
Is it right what I understood? What do you mean exactly by saying "So we could define a cross-linker that links Protein-N-terminal methionine or KSTY anywhere else to anything as"?

**Comment by lutzfischer** [comment]
@timosachsenberg yes that case is currently not really supported. What we could do is to extend the format to something like (K)&(Y)|(S)&(T). Only is there a cross-linker like that? And if it is does it have the same composition in both cases?

**Comment by lutzfischer** [comment]
@sulezinha  Sorry for the confusion. 
The example was a theoretical one - not currently used for any cross-linekr. DSS is currently defined with (K,S,T,Y,N-term)&(K,S,T,Y,N-term). 
Meaning from and to K,S,T,Y or N-terminal without restriction as to what amino-acid is at the N-terminal. 

As to whether the second amino-acid is a valid N-terminal depends on a lot of things - like whether your looking at bacteria or not and what is the second amino-acid. For the exact rules for this you have to ask an expert in that field...  As a generalised approach we also consider the N-terminal methionine and the following amino-acid as valid n-terminal. If the sequence start with something else then M only the N-terminal residue is considered. 
But I don't think that is something we should try encode within the cross-linker specificities.

**Comment by andrewrobertjones** [comment]
@lutzfischer is going to update the CV with the n-term specs. Agree for now the theoretical case raised by @timosachsenberg is not needed at the moment
