### ISSUE TITLE
Manual annotation of PSMs

### ISSUE THREAD

**Issue by enetz** [HUPO-PSI/mzIdentML#14]
We briefly discussed at the PSI meeting, that manual annotations would be possible by manually setting the passThreshold value in SpectrumIdentificationItem.
Since manual examination of spectra is still very important in cross-linking pipelines, could we add more flexible annotations, maybe a CV term for free text comments?
Manually changing the passThreshold flag would not be transparent and reproducible.
Or is there a good reason to generally avoid such free text comments?

**Comment by andrewrobertjones** [comment]
Hi @enetz Anyone is free to add any types of CV terms you want to SpectrumIdentificationItem. Please make some suggestion for what such a term would look like, and then we will add it in. It doesn't need to be part of the formal standard

**Comment by mwalzer** [comment]
Sure we could put 'free form' annotations in there, but the question is @enetz to what extent we would want to make these annotations machine readable for others (e.g. for visualising). _Are there common operations in manual annotation?_
I'd guess something along the lines of ```manual peak tagging``` or ```manual peak annotation``` and ```manual peak group tagging```.

**Comment by andrewrobertjones** [comment]
Here are some CV terms already in existence:

`
[Term]
id: MS:1001125
name: manual validation
def: "Result of quality estimation: decision of a manual validation." [PSI:PI]
xref: value-type:xsd\:string "The allowed value-type for this CV term."
is_a: MS:1001092 ! peptide identification confidence metric
is_a: MS:1001198 ! protein identification confidence metric

[Term]
id: MS:1001058
name: quality estimation by manual validation
def: "The quality estimation was done manually." [PSI:PI]
is_a: MS:1001060 ! quality estimation method details
`

Please try them out in your files and see if they pass validation. If they do, let's just go with that, and I can add a point in the spec doc recommending to use them - probably  MS:1001125 for XL ident validation
