### ISSUE TITLE
How to annotate reporter ions as part of the Fragmentation section?

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#16]
Related to https://github.com/HUPO-PSI/mzIdentML/issues/9, are there any of examples of how reporter ions from, for example, iTRAQ and TMT are to be annotated as part of the Fragmentation section? I could not find the required CV terms?

**Comment by andrewrobertjones** [comment]
This is part of the documentation in the schema: "For any other ions not related to the position within the peptide sequence e.g. quantification reporter ions, the index value MUST be 0."

Please request the terms for PSI-MS CV for specific reporter ions you want to annotate
