### ISSUE TITLE
Is the DenovoSearchType_may_rule used correctly?

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#17]
What is the purpose of the DenovoSearchType_may_rule? I get the following for the PeptideShaker mzid 1.2 example file:

Rule ID: DenovoSearchType_may_rule 
    Level: INFO
    Context(/additionalSearchParams/cvParam/@accession ) in 2 locations
    --> Not all of the 6 values ParamList's CV terms ['MS:1001211', 'MS:1001256', 'MS:1002492', 'MS:1002490', 'MS:1002497', 'MS:1002491'] found using the Xpath '/additionalSearchParams/cvParam/@accession' matched any of the 1 CvTerm(s):
  - The sole term MS:1001010 (de novo search) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.

But this is not a de novo search. Shouldn't this rule only be triggered for mzid files that appear to be de novo searches?

**Comment by andrewrobertjones** [comment]
Gerhard unable to reproduce issue. Harald re-open if it is still a problem
