### ISSUE TITLE
Validator has issues with new threshold CV terms for mzid 1.1 files

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#18]
If I recreate the PeptideShaker mzid 1.2 example file but remove all the new 1.2 additions, i.e., creating an mzid 1.1 compatible file, the validator is not happy and gives the following errors:

Message 1:
    Rule ID: ProteinDetectionProtocolThreshold_rule
    Level: ERROR
    Context(/threshold/cvParam/@accession ) in 2 locations
    --> The result found at: /threshold/cvParam/@accession for which the values is  ''MS:1002369'' didn't match any of the 4 specified CV terms:
  - The sole term MS:1001447 (prot:FDR threshold) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - The sole term MS:1001494 (no threshold) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - Any children term of MS:1001153 (search engine specific score). The term can be repeated. The matching value has to be the identifier of the term, not its name.
  - Any children term of MS:1001302 (search engine specific input parameter). The term can be repeated. The matching value has to be the identifier of the term, not its name.

Message 2:
    Rule ID: SpectrumIdentificationProtocolThreshold_must_rule
    Level: ERROR
    Context(/threshold/cvParam/@accession ) in 2 locations
    --> The result found at: /threshold/cvParam/@accession for which the values are  ''MS:1001364', 'MS:1002350', 'MS:1002567', 'MS:1002557'' didn't match any of the 4 specified CV terms:
  - The sole term MS:1001448 (pep:FDR threshold) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - The sole term MS:1001494 (no threshold) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - Any children term of MS:1001153 (search engine specific score). The term can be repeated. The matching value has to be the identifier of the term, not its name.
  - Any children term of MS:1001302 (search engine specific input parameter). The term can be repeated. The matching value has to be the identifier of the term, not its name.

Both seem to be due to the validator not considering new currently supported threshold terms?

In the first message it says that "MS:1001447 (prot:FDR threshold) or any of its children" ought to be used. I think the correct term now is "MS:1002572  (protein detection statistical threshold) or any of its children"? As this covers the new "protein group-level statistical threshold" terms?

Similar for the second message: "MS:1001448 (pep:FDR threshold) or any of its children" ought to be changed into "MS:1002484 (peptide-level statistical threshold) or any of its children"?

**Comment by germa** [comment]
Resolved.
