### ISSUE TITLE
Cross-linking CV

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzIdentML#2]
The following tasks are needed for the cross-linking CV:

- Hosting here on GitHub (CSV format?)
- Unique identifiers for all cross-link and dead-end mods
- Put identifiers into XL example documents

**Comment by andrewrobertjones** [comment]
We need a new branch of the PSI-MS CV for "protein interaction scores derived from cross-linking" @germa . Child terms derived from here MUST have a data type following a regular expression:

The CV term value MUST have the structure of: “FILE_UNIQUE_IDENTIFIER:SCORE” – where FILE_UNIQUE_IDENTIFIER is an integer unique (at the file level) to the interaction pair and SCORE is the score or statistical value assigned to the interaction score. The name of the CV term should state the type of interaction score or statistic. 

In the mapping file, the parent branch MUST be mapped from ProteinAmbiguityGroup - CHILD terms allowed.

**Comment by javizca** [comment]
Maybe it is worth checking the PSI-MS CV first, to see if these scores are already there. I know that at least some work has already been done in this context there.

**Comment by lutzfischer** [comment]
I uploaded a initial list of cross-linker. Several points I would make:
* Having a all site specificities as a list in on field seems to me the more future proof then having one filed per site and then adding new fields if somebody wants to express something else then dimeric cross-linker
* having a field that denotes just the number of reactive sites on a cross-linker
 *  less discussion about how we call what.

* how do we treat ms-cleavable cross-linker (e.g. DSSO)
 * do we store the cross-link product or the identified modifications?
 * possibly both and link them up?
* We have separate entries for the cross-linker and cross-linker with one site e.g. hydrolized
 * do we somehow flag these up as belonging together?
* We have a field "Reference" currently mostly with thermo links
 * I would prefer something less specific to a company e.g. a publication describing/using the cross-linker
  * who looks up the paper?
* what is the minimum requirement we want for adding something to the list?

**Comment by lutzfischer** [comment]
Some points for thought about Cross-linking site localisation
 * Is a psm/peptide-level site localisation enough
 * the actual residue pair (as in residue 255 of protein a is linked to residue 136 of protein2) might have different site-localisation  probability then the links on each supporting psm. 
  * e.g. applying occams razor and ignoring site localisation on PSM level beyond the simple "it could be this or that").

if we want to store both level of information we could duplicate the peptide-level scores for a protein level score on each PSM, or store these as a list of cvParams on each protein. 
We could also require, that only one of these cases are permitted to be stored and then we could just go with what we have - at least i think it would do.

**Comment by mwalzer** [comment]
@lutzfischer
> I uploaded a initial list of cross-linker.

Can you post a link, please?

**Comment by lutzfischer** [comment]
https://github.com/HUPO-PSI/mzIdentML/blob/master/cv/XLMOD.csv

**Comment by andrewrobertjones** [comment]
In response to @lutzfischer I agree that cross-linker site localisation evidence could be added at the level of the protein, and this would need to go on ProteinDetectionHypothesis in mzid (i.e. accession level rather than protein group level), something like as follows:

INTERACTION_PAIR_ID:PROTEIN_SEQ_POSTION:SCORE:PASS_THRESHOLD - similar to mod localization. 

Question - is anything needed at the ProteinGroup level simply assessing the evidence that a pair of proteins are interacting, where you don't care about positional info?

**Comment by lutzfischer** [comment]
@andrewrobertjones would it make sense to abstract the cross-linker position to a modification localisation? The problem there would be that you would have to encode more complicated cases then we currently have/usually care about in cross-linking. E.g. that two sites are mutual exclusive. But how much more would we need to have general modifications covert?

**Comment by lutzfischer** [comment]
@andrewrobertjones if we put the info on individual proteins we probably need to flag up the site as well. Otherwise we have problems to distinguish a link that could come from protein A residue X and could end in either protein B residue Y OR protein C residue Z. E.g. extend the info to
INTERACTION_PAIR_ID:CROSSLINK_ID:SITE_ID:PROTEIN_SEQ_POSTION:SCORE:PASS_THRESHOLD

As to if we need a another info on protein group level - I would say yes. A link could have a 5% chance of being wrong - bit the supported protein interaction could actually have something a lot worse or better than that. So we would want to be able to flag that up as well.

**Comment by andrewrobertjones** [comment]
I think changing interaction id to be integer.a integer.b e.g. 1001.a 1001.b for the interacting partners would work for this. Then the same value could be shared amongst different proteins within same group, showing ambiguity rather than implying they are interacting. Coupled with my proposal higher up, this would seem to cover most cases needed?

**Comment by mwalzer** [comment]
thread is getting too long, will just reference related issues here:
#13 
#20
