### ISSUE TITLE
Cross-linking - protein interaction evidence

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzIdentML#24]
I have closed down long convoluted thread on various CV items: #2. 

The have made a proposal for how I think we should represent protein interaction evidence in mzid - see attached pdf.
[xl_protein_interaction.pdf](https://github.com/HUPO-PSI/mzIdentML/files/248648/xl_protein_interaction.pdf)

**Comment by andrewrobertjones** [comment]
Overall agreement on call that this looks okay for now. Lutz will make proposal for CV terms for his software.

**Comment by andrewrobertjones** [comment]
@germa - Can you update the validator to check the regex structure for Lutz examples.

**Comment by germa** [comment]
Shouldn't it be accession = Prot C.1 inside PDH 1.1 of PAG 3 (in the left figure) ?

**Comment by andrewrobertjones** [comment]
@lutzfischer can you re-check the validator to see if everything is now okay

**Comment by andrewrobertjones** [comment]
@lutzfischer  would you mind reporting back if your files are now passing the validator and all seems okay? thanks Andy

**Comment by germa** [comment]
The two examples from Lutz:
xiFDR-CrossLinkExample.mzid and
xiFDR-CrossLinkExample_single_run.mzid
are validate now, since loop-links are also allowed by the validator.
