### ISSUE TITLE
MS:1001355 peptide descriptions

### ISSUE THREAD

**Issue by germa** [HUPO-PSI/mzIdentML#27]
Can we make the following term obsolete?

[Term]
id: MS:1001355
name: peptide descriptions
def: "Descriptions of peptides." [PSI:PI]
is_a: MS:1001105 ! peptide result details

It has no children and no associated value, so it makes not much sense.

**Comment by andrewrobertjones** [comment]
Agreed to leave this in as a place holder to allow for extensions in the future
