### ISSUE TITLE
CV priority, Unimod or XLMOD if both applicable?

### ISSUE THREAD

**Issue by enetz** [HUPO-PSI/mzIdentML#28]
Some of the cross-linkers have CV terms in Unimod, e.g. the mono-links for DSS (but not the cross-link).
If there are CV terms in Unimod available, should the Unimod terms be used, or should the XLMOD terms from the csv file have priority for cross-linking specific information?
The cross-link CV terms in Unimod are patchy, so if we prioritize Unimod we will have both Unimod and XLMOD terms in most files. Otherwise we could cover all cross-linking specific information with XLMOD terms and be more uniform.

**Comment by andrewrobertjones** [comment]
We agree that either Unimod or XLMOD CV is fine
