### ISSUE TITLE
Mod re-scoring

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzIdentML#3]
I have opened an issue here to make sure that:

1. There are valid CV terms for mod rescoring
2. Example files are correctly validated.
3. The spec doc is correct and up-to-date. 

Please add any other issues related to mod rescoring. We will close it once all is complete. I've assigned it to Harald - hope that is okay!

**Comment by hbarsnes** [comment]
@andrewrobertjones I decided to add the them as separate issues instead as I think this is clearer and easier to maintain. So please add more if there is something I forgot.

**Comment by hbarsnes** [comment]
@andrewrobertjones @germa 
Quick update on the validation of the PeptideShaker mzid 1.2 example file. After Gerhard's recent fixes the file now validates without any errors and with a lot less INFO messages. The remaining messages mainly relate to additional CV terms that could be added but that are not mandatory. 

There are only three remaining questions, all set up as separate issues: 
- Allow search statistics children terms: https://github.com/HUPO-PSI/mzIdentML/issues/8
- Use of the DenovoSearchType_may_rule: https://github.com/HUPO-PSI/mzIdentML/issues/17
- How to annotate immonium ions: https://github.com/HUPO-PSI/mzIdentML/issues/9

And on a related note to the last point, what about reporter ions? See: https://github.com/HUPO-PSI/mzIdentML/issues/16.

**Comment by andrewrobertjones** [comment]
All ported to new issues - closing
