### ISSUE TITLE
Validator: too strict on "cross-link spectrum identification item" values

### ISSUE THREAD

**Issue by enetz** [HUPO-PSI/mzIdentML#31]
The CV accession="MS:1002511" name="cross-link spectrum identification item" must have the same value for SIIs that represent a pair of cross-linked peptides.
Currently the validator only allows exactly two equal values, but we have 4 SIIs for the same cross-link when using isotope labelled linkers.

**Comment by andrewrobertjones** [comment]
Discussed the correct behaviour should be to check 2 or 4 having the same value --> 4 for the case of stable isotopes only

**Comment by mwalzer** [comment]
@germa can you please add this to the validator?

**Comment by germa** [comment]
@matthias The allowed value 4 is already added; in case it does not work, please send me an example file

**Comment by mwalzer** [comment]
@germa thx Gerhard! 

(btw, @matt... not my handle :smile: )
