### ISSUE TITLE
Cross-Linking fragment annotations

### ISSUE THREAD

**Issue by enetz** [HUPO-PSI/mzIdentML#32]
We are trying to implement fragment annotations for cross-linked peptides in OpenMS and uploaded an [example file here](https://github.com/HUPO-PSI/mzIdentML/blob/master/examples/1_2examples/crosslinking/OpenxQuest_example_added_annotations.mzid).
In the case of cross-linking we have fragments resulting from cleavages of both peptides in one spectrum. Therefore distributing the annotations between several SIIs would make further usage e.g. visualization of these annotations more complicated and the separation would not be possible in more complex fragmentation patterns, e.g. cross-linked fragments where both peptides were cleaved. So we would prefer to store the annotations for one PSM under one SII, e.g. the light alpha case.

The example suggests adapting FragmentArray to also carry strings (words) or have an additional array carrying these (not in the example). 
The specific CVs we would need are:
One Array for "cross-link chain" containing CV strings for "donor" or "acceptor" for each fragment.
One Array for "cross-link ion category" containing CV strings for "common ion" or "cross-linked ion" for each fragment.
The example file shows roughly how that could look like.

Another way to do it would be to introduce additional IonTypes and therefore separate these types into different arrays. In that case we would need all four combinations of donor/receiver with common/cross-linked

**Comment by mwalzer** [comment]
For any software it would not make much sense to rip apart the annotations to one spectrum - and puzzle it back together.  - Though this would solve the problem of denoting alpha/beta, not so for ci/xi ions.

**Comment by mwalzer** [comment]
If we would decide to introduce CVs like frag: y ion - alpha, ... this would also add to the bloat of the file, as there would be more  ```<IonType>``` elements. This would also bloat the CV.

**Comment by mwalzer** [comment]
**One idea** would be to allow strings in the values of ```<FragmentArray>``` elements and by convention let these strings be accessions to CVs defined in the ```<Measurement>```.

**The other** would be to introduce an additional abstraction of ```<FragmentArray>``` for ```<FragmentCVREFArray>```.  ```<Measurement>``` for these would have to be allowed to carry several cv, one for each possible type of annotation flag.

**Comment by andrewrobertjones** [comment]
We briefly discussed this in Ghent, and felt that it would be a lot of work for fairly minimal gain to get into mzid 1.2. The fragment ion annotation part isn't widely used anyway, and I would be happy to vote that for XL data it is not formally supported. At least for now. Thoughts?

**Comment by mwalzer** [comment]
I would not mind if that's not formally supported if we could informally represent that. Problem is that it is quite unflexible on the array/measure site. So this would actually thwart the chance to take 'the last mile' with mzid only. 
We could however do (informally) with a ```<ParamGroup>``` in ```<IonType>``` (right now cvParams only).

**Comment by mwalzer** [comment]
A cleaner way would be an additional data type. Which I guess would be too much of an extra workload for v1.20, but for future reference I draft a proposal:
![fragarrcvtag](https://cloud.githubusercontent.com/assets/5859205/15710477/7d551706-280a-11e6-86b9-3293f0ce7bbb.png)
```
<xsd:complexType name="FragmenCVTagArrayType">
	<xsd:annotation>
		<xsd:documentation>An array of cvTerm references for a given type of measure and for a particular ion type, in parallel to the index of ions identified. (Each indexed ion can be tagged with a cv)</xsd:documentation>
	</xsd:annotation>
	<xsd:attribute name="values" type="listOfCVRefs" use="required">
		<xsd:annotation>
			<xsd:documentation>The values of this particular measure, corresponding to the index defined in ion type </xsd:documentation>
		</xsd:annotation>
	</xsd:attribute>
	<xsd:attribute name="measure_ref" type="xsd:string" use="required">
		<xsd:annotation>
			<xsd:documentation>A reference to the Measure defined in the FragmentationTable. The measure will predefine the cvTerms available to tag ions with. (?uch might be the group of either alpha or beta chain ions or the group of either manually or automatically annotated ions)</xsd:documentation>
		</xsd:annotation>
	</xsd:attribute>
</xsd:complexType>
<xsd:simpleType name="listOfCVRefs">
	<xsd:list itemType="cvRef"/>
</xsd:simpleType>
<xsd:simpleType name="cvRef">
	<xsd:restriction base="xsd:string">
		<xsd:pattern value="\w*:\d*"/>
	</xsd:restriction>
</xsd:simpleType>
```

**Comment by mwalzer** [comment]
As example for how this could work with userParams
```
<IonType charge="3" index="7 6">
    <FragmentArray measure_ref="Measure_mz" values="234.32 321.23"/>
    <FragmentArray measure_ref="Measure_Int" values="123 345"/>
    <userParam name="frag: y ion" values="MS:10xxxx1 MS:10xxxx2"/>
</IonType>
```

**Comment by mwalzer** [comment]
This could also work out with allowing for *strings* in ```<FragmentArray>```  (now only *double* values)

**Comment by andrewrobertjones** [comment]
Agreed to add userParams to cover this case - I will action this change in the schema
