### ISSUE TITLE
generic neutral loss term with value slot for the formula

### ISSUE THREAD

**Issue by germa** [HUPO-PSI/mzIdentML#34]
Should we define a generic neutral loss term as proposed by Steffen Neumann,
see https://sourceforge.net/p/psidev/mailman/psidev-ms-vocab/?viewmonth=201605&viewday=25

and should be the terms
id: MS:1002455 ! H2O neutral loss, 
id: MS:1002456 ! NH3 neutral loss and 
id: MS:1002457 !  H3PO4 neutral loss
then be made obsolete?

**Comment by andrewrobertjones** [comment]
Agreed to this change

e.g.

<cvParam name = "neutral loss" value = "H2O"/>

@germa  Can you action this, and I will add this to the spec doc

**Comment by germa** [comment]
Done in version 3.89.0 of psi-ms.obo
