### ISSUE TITLE
Validation issues with OpenxQuest_example.mzid

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#37]
ERROR: cvParam retention time should have units, but it does not!
ERROR: cvParam search engine specific score for PSMs has a value, but it should not!
WARNING: cvParam product ion intensity has a legal unit MS:1000131 but its name 'MS:1000131' should be 'number of detector counts'!
WARNING: MS:1002510 should be 'cross-link acceptor' instead of 'cross-link receiver'

**Comment by andrewrobertjones** [comment]
Solved
