### ISSUE TITLE
Validation issues with Panalyzer* files

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#41]
These files do not properly reference that they are mzIdentML 1.2. Mixed references to 1.1 and 1.2
<MzIdentML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="" xsi:schemaLocation="http://psidev.info/psi
/pi/mzIdentML/1.1 mzIdentML1.1.0.xsd" creationDate="2014-06-03T14:54:40.852156Z" version="1.2.0" xmlns="http://psidev.info/psi/pi/mzIdentML/1.1">
cannot validate

**Comment by javizca** [comment]
I will contact Gorka

**Comment by akrogp** [comment]
Solved in commit d3504bfb519ee382109aa58d3dd7d59a87a672fe
