### ISSUE TITLE
Referencing CVs

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#42]
Many/most of the mzIdentML files do not reference the CVs properly. All files should be checked and corrected.

I believe that the correct CV locations should be:
https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo
https://raw.githubusercontent.com/bio-ontology-research-group/unit-ontology/master/unit.obo

Is that right? Corrections welcome.

**Comment by mwalzer** [comment]
I second that.  :+1:

**Comment by germa** [comment]
yes, the https://raw.githubusercontent.com/... links are the correct ones.
