### ISSUE TITLE
Difference between two XLMOD files?

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#44]
What is the distinction between:
XLMOD-1.0.0.csv
XLMOD.csv

It would be nice to have a proper OBO file for my validator, but I could code up handling for csv. What does the Java validator do?

XLMOD-1.0.0.csv shows this:
XL:00001,Xlink:BS3,2,138.06807961,"(K,S,T,Y,Protein N-term)&(K,S,T,Y,Protein N-term)"

while XLMOD.csv shows this:
XL:00001,BS3,bis(sulfosuccinimidyl)suberate,https://www.thermofisher.com/order/catalog/product/21580,Xlink:BS3,BS3,2,138.06807961,138.16,"C8 H10 O2",
"(K,S,T,Y,Protein N-term)&(K,S,T,Y,Protein N-term)"

The latter seems to be the more complete one?
I hope we're leaving the "Xlink:" prefix behind as not needed?

**Comment by germa** [comment]
By some reasons, which I forgot, we decided to use at first onls the minimal version (Issue #20).
I created now an .obo file out of that Excel sheet.
@Lutz: Can you double check, if all is encoded ok (I added a definition for each cross-linker).

**Comment by andrewrobertjones** [comment]
@mwalzer agreed to rename or put in sub-folder

**Comment by mwalzer** [comment]
Thanks @germa for converting to obo. I added a readme to the subfolder, mentioning the active file is now the obo and csv should be versioned accordingly to help syncing up. Feel free to edit the README.md with instructions.
