### ISSUE TITLE
Crash of Validator (on invalid file)

### ISSUE THREAD

**Issue by julianu** [HUPO-PSI/mzIdentML#47]
I get a reproducible crash of the validator (1.4.18) when trying to validate the attached file:[pia_testMzIdentML.mzId.gz](https://github.com/HUPO-PSI/mzIdentML/files/315992/pia_testMzIdentML.mzId.gz

The file is erroneous, but still the validator should not crash. After the last uncatched exception, the GUI stay where it is, pretending to do something.

This is the output on the console:

> $ java -Xmx8G -jar mzIdentMLValidator-1.4.18-SNAPSHOT.jar 
> BrendaTissueOBO.obo
> gene_ontology.obo
> psi-ms.obo
> PSI-MOD.obo
> pato.obo
> unimod.obo
> unit.obo
> 
> 
> There were errors validating against the XML schema:
> 
> 	 - ValidatorMessage{message='Non-fatal XML Parsing error detected on line 20215
>   Error message: cvc-complex-type.2.4.b: The content of element 'AnalysisCollection' is not complete. One of '{"http://psidev.info/psi/pi/mzIdentML/1.1":SpectrumIdentification}' is expected.', level=ERROR, context=null, rule=null}
> 	 - ValidatorMessage{message='Non-fatal XML Parsing error detected on line 41189
>   Error message: Key 'FK_SoftwareContact' with value 'ORG_MSL' not found for identity constraint of element 'MzIdentML'.', level=ERROR, context=null, rule=null}
> 	 - ValidatorMessage{message='Non-fatal XML Parsing error detected on line 20216
>   Error message: cvc-complex-type.2.4.b: The content of element 'AnalysisProtocolCollection' is not complete. One of '{"http://psidev.info/psi/pi/mzIdentML/1.1":SpectrumIdentificationProtocol}' is expected.', level=ERROR, context=null, rule=null}
> 	 - ValidatorMessage{message='Non-fatal XML Parsing error detected on line 20261
>   Error message: cvc-complex-type.4: Attribute 'id' must appear on element 'SpectrumIdentificationList'.', level=ERROR, context=null, rule=null}
> Number of rules to check: 35
> Exception in thread "Thread-1" java.lang.IllegalStateException: Could not instantiate reference resolver: uk.ac.ebi.jmzidml.xml.jaxb.resolver.ContactRoleRefResolver
> 	at uk.ac.ebi.jmzidml.xml.jaxb.unmarshaller.listeners.RawXMLListener.referenceResolving(RawXMLListener.java:192)
> 	at uk.ac.ebi.jmzidml.xml.jaxb.unmarshaller.listeners.RawXMLListener.afterUnmarshal(RawXMLListener.java:55)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.fireAfterUnmarshal(Loader.java:221)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.leaveElement(StructureLoader.java:276)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.endElement(UnmarshallingContext.java:585)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:165)
> 	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
> 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
> 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
> 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
> 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
> 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
> 	at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:273)
> 	at uk.ac.ebi.jmzidml.xml.io.MzIdentMLObjectIterator.next(MzIdentMLObjectIterator.java:88)
> 	at uk.ac.ebi.jmzidml.xml.io.MzIdentMLObjectIterator.next(MzIdentMLObjectIterator.java:41)
> 	at psidev.psi.pi.validator.MzIdentMLValidator.checkElementCvMapping(MzIdentMLValidator.java:1143)
> 	at psidev.psi.pi.validator.MzIdentMLValidator.applyCVMappingRules(MzIdentMLValidator.java:779)
> 	at psidev.psi.pi.validator.MzIdentMLValidator.doValidationWork(MzIdentMLValidator.java:511)
> 	at psidev.psi.pi.validator.MzIdentMLValidator.startValidation(MzIdentMLValidator.java:429)
> 	at psidev.psi.pi.validator.MzIdentMLValidatorGUI$4.construct(MzIdentMLValidatorGUI.java:681)
> 	at psidev.psi.pi.validator.swingworker.SwingWorker.lambda$new$1(SwingWorker.java:138)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by julianu** [comment]
This bug seems to be related to these lines in the mzIdentML inside the analysisSoftware, which should be correct:

`<ContactRole contact_ref="ORG_MSL">`
`  <Role>`
`    <cvParam cvRef="PSI-MS" accession="MS:1001267" name="software vendor"></cvParam>`
`  </Role>`
`</ContactRole>`

**Comment by mwalzer** [comment]
I read there something about mzid 1.1 - is also related #41?

**Comment by julianu** [comment]
crash is fixed and shows an error in 72ba158dbcb155135f1fdb8397b915236f6a67dc
