### ISSUE TITLE
Duplicate mapping files

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#56]
There seem to be two mapping files in the repo. I have been using:

33846 Mar 31 12:43 cv/mzIdentML-mapping_1.2.0.xml

But this one seems larger and is perhaps the right one?
41666 Jun 23 10:38 validator/trunk/src/main/resources/mzIdentML-mapping_1.2.0.xml

If the one in cv/ is obsolete, we should either make sure they are sync'ed, or only have one copy.

Or would you let me know if there is an important difference?

**Comment by germa** [comment]
It seems there are much more old files in that folder:

DONT_USE_axml-mapping.xml
DONT_USE_psi-pi.obo
mzIdentML-mapping.xml
mzIdentML-mapping_1.1.0.xml
mzIdentML-mapping_1.2.0.xml
search_engine_outputs.xls
unimod.obo

and also the subfolder old and the files therein.

I propose to delete them.

**Comment by andrewrobertjones** [comment]
@germa - thanks, can you delete from the CV folder and add a README.txt explaining where to find them
