### ISSUE TITLE
URI problem with mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#58]
And this file doesn't pass my XML validator with these errors:

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid, line 352, char 146
  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'C:\Work\PSI\mzIdentML\ProteinInference\Rosetta2\tandem\peaklist2a_plus_ecoli_versus_unimod_full.xml' is NOT a valid URI .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid, line 357, char 197
  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'C:/Work/PSI/mzIdentML/ProteinInference/Rosetta2/FASTAs, neat/Rosetta_uniprot_20130402_mouse_FULL_UNIPROT_can+iso.fasta' is NOT a valid URI .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid, line 365, char 151
  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'C:/Work/PSI/mzIdentML/ProteinInference/Rosetta2/Peak lists with ecoli/Rosetta peak list 2a + Ecoli spectra.mgf' is NOT a valid URI .

URIs need to start with file:/// for local files I think.

And they may not contain spaces.

**Comment by andrewrobertjones** [comment]
@fghali  Would you mind fixing these and try running the file past the latest mzid validator: https://github.com/HUPO-PSI/mzIdentML/releases

**Comment by fghali** [comment]
I have update the example file and changed '/' to '\' and removed the spaces from the file name.

**Comment by edeutsch** [comment]
Today's validation says:
Validating for XSD conformation in file mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid, line 348,
 char 146
  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'C:\Work\PSI\mzIdentML\ProteinInference\Rosetta2\tandem\peaklist2a_plus_
ecoli_versus_unimod_full.xml' is NOT a valid URI .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid, line 353,
 char 191
  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'C:\Work\PSI\mzIdentML\ProteinInference\Rosetta2\FASTAs\Rosetta_uniprot_
20130402_mouse_FULL_UNIPROT_can_iso.fasta' is NOT a valid URI .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid, line 361,
 char 135
  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'C:\Work\PSI\mzIdentML\ProteinInference\Rosetta2\Peak_lists_with_ecoli\R
osetta_peak_spectra.mgf' is NOT a valid URI .

I think the issue is that you can't start a URL with C:\. URIs have to start with file:/// or something like that.

**Comment by fghali** [comment]
I've changed the URI to start with file:/// but I cannot tell if this fix the URI issue since I cannot reproduce it.

**Comment by edeutsch** [comment]
This file appears fully valid now, thanks.
