### ISSUE TITLE
URI problem with mzidLib_rosetta_2a_uniprot_proteogrouped.mzid

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#59]
Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/mzidLib_rosetta_2a_uniprot_proteogrouped.mzid, line 3474, char 72
  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'file:///Rosetta peak list 2a.mgf' is NOT a valid URI .

URIs may not have spaces in them according to my Xerces validator

**Comment by fghali** [comment]
Done.
