### ISSUE TITLE
more structure in XLMOD.obo

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#60]
I think it would be very valuable to add some hierarchical structure to XLMOD.obo. right now there are no parents. I propose that we have a top-level term, perhaps similar to the PSI-MS top term:

[Term]
id: XL:00000
name: Proteomics Standards Initiative cross-linking controlled vocabulary
def: "Proteomics Standards Initiative cross-linking controlled vocabulary." [PSI:XL]

and then a child something like:

[Term]
id: XL:00012
name: cross-linking entity
def: "Entity relevant to the domain of cross-linking in proteomics." [PSI:XL]
is_a: XL:00000 ! Proteomics Standards Initiative cross-linking attribute
relationship: part_of XL:00000 Proteomics Standards Initiative cross-linking controlled vocabulary

[Term]
id: XL:00013
name: cross-linker
def: "Compound that can link one polymer chain to another." [PSI:XL]
is_a: XL:00012 ! cross-linking entity

This would allow us to grow the CV in a more tidy fashion, plus would allow the mapping file to stipulate that location X is the right place to put a child of XL:00013. I don't think this is possible in the current layout.

What do you think?

**Comment by germa** [comment]
maybe we can structure it even further like e.g.

[Term]
id: XL:00000
name: Proteomics Standards Initiative cross-linking controlled vocabulary
def: "Proteomics Standards Initiative cross-linking controlled vocabulary." [PSI:XL]

[Term]
id: XL:00001
name: cross-linking entity
def: "Entity relevant to the domain of cross-linking in proteomics." [PSI:XL]
relationship: part_of XL:00000 Proteomics Standards Initiative cross-linking controlled vocabulary

[Term]
id: XL:00002
name: cross-linker
def: "Compound that can link one polymer chain to another." [PSI:XL]
is_a: XL:00001 ! cross-linking entity

[Term]
id: XL:00003
name: monofunctional cross-linker
def: "A cross-linker reagent with one reactive group." [PSI:XL]
is_a: XL:00002 ! cross-linker

[Term]
id: XL:00004
name: bifunctional cross-linker
def: "A cross-linker reagent with two reactive groups." [PSI:XL]
is_a: XL:00002 ! cross-linker

[Term]
id: XL:00005
name: homobifunctional cross-linker
def: "A cross-linker reagent with identical reactive groups at either end of the spacer arm." [PSI:XL]
is_a: XL:00004 ! bifunctional cross-linker

[Term]
id: XL:00006
name: heterobifunctional cross-linker
def: "A cross-linker reagent with different reactive groups at either end of the spacer arm." [PSI:XL]
is_a: XL:00004 ! bifunctional cross-linker

[Term]
id: XL:00007
name: photoreactive cross-linker
def: "A cross-linker reagent that becomes reactive when exposed to ultraviolet or visible light." [PSI:XL]
synonym: "non-selective cross-linker" EXACT [PSI:XL]
is_a: XL:00002 ! cross-linker

[Term]
id: XL:00008
name: trifunctional cross-linker
def: "A cross-linker reagent acting as label (e.g. biotin) transfer reagent." [PSI:XL]
is_a: XL:00002 ! cross-linker

[Term]
id: XL:00009
name: zero-length cross-linker
def: "A cross-linker reagent causing direct conjugation of carboxylates (-COOH) to primary amines (-NH2) without becoming part of the final crosslink (amide bond) between the target molecules." [PSI:XL]
is_a: XL:00002 ! cross-linker

**Comment by lutzfischer** [comment]
Some points:
> [Term]
> id: XL:00003
> name: monofunctional cross-linker
> def: "A cross-linker reagent with one reactive group." [PSI:XL]
> is_a: XL:00002 ! cross-linker

Don't think you could call that a cross-linker in the sense of XL:00002
Can we call it something along the lines of "cross-linker related PTM" or "cross-linker derived PTM"

Also 
> [Term]
> id: XL:00008
> name: trifunctional cross-linker
> def: "A cross-linker reagent acting as label (e.g. biotin) transfer reagent." [PSI:XL]
> is_a: XL:00002 ! cross-linker

 trifunctional is ambiguous - you can have three groups on a cross-linker - but for some cross-linker that is used purification (e.g. biotin) on others that is just another group that is supposed to react with amino-acids (e.g. three nhs-ester groups.) 

So maybe could name this to 
> [Term]
> id: XL:00008
> name: label transfer reagent
> def: "label (e.g. biotin) transfer reagent." [PSI:XL]

and flag Terms with an has relationship.

Lastly
> [Term]
> id: XL:00005
> name: homobifunctional cross-linker
> def: "A cross-linker reagent with identical reactive groups at either end of the spacer arm." [PSI:XL]
> is_a: XL:00004 ! bifunctional cross-linker
> 
> [Term]
> id: XL:00006
> name: heterobifunctional cross-linker
> def: "A cross-linker reagent with different reactive groups at either end of the spacer arm." [PSI:XL]
> is_a: XL:00004 ! bifunctional cross-linker

Can we rename these to homofunctional and heterofunctional? And not flag them as bifunctional?

Do we need to have separate categories for bifunctional? We have the number of reatcive sites as part of the cross-linker definition.



```
[Term]
id: XL:00000
name: Proteomics Standards Initiative cross-linking controlled vocabulary
def: "Proteomics Standards Initiative cross-linking controlled vocabulary." [PSI:XL]


[Term]
id: XL:00001
name: cross-linking entity
def: "Entity relevant to the domain of cross-linking in proteomics." [PSI:XL]
relationship: part_of XL:00000 Proteomics Standards Initiative cross-linking controlled vocabulary

[Term]
id: XL:00002
name: cross-linker
def: "Compound that can link two or more polymer chain." [PSI:XL]
is_a: XL:00001 ! cross-linking entity

[Term]
id: XL:00003
name: cross-linker related PTM
def: "A cross-linker reagent with one reactive group." [PSI:XL]
relationship: part_of XL:00000 Proteomics Standards Initiative cross-linking controlled vocabulary

[Term]
id: XL:00004
name: homo-functional cross-linker
def: "A cross-linker reagent with identical reactive groups at each end of the spacer arm." [PSI:XL]
is_a: XL:00002 ! cross-linker

[Term]
id: XL:00005
name: hetero-functional cross-linker
def: "A cross-linker reagent with at least two different reactive groups." [PSI:XL]
is_a: XL:00002 ! cross-linker

[Term]
id: XL:00006
name: photoreactive cross-linker
def: "A cross-linker reagent that becomes reactive when exposed to ultraviolet or visible light." [PSI:XL]
synonym: "non-selective cross-linker" EXACT [PSI:XL]
is_a: XL:00002 ! cross-linker

[Term]
id: XL:00007
name: label transfer reagent
def: "NOT SURE WHAT TO WRITE HERE" [PSI:XL]
relationship: part_of XL:00000 Proteomics Standards Initiative cross-linking controlled vocabulary

[Term]
id: XL:00008
name: zero-length cross-linker
def: "A cross-linker reagent causing direct conjugation without becoming part of the final crosslink  between the target molecules." [PSI:XL]
is_a: XL:00002 ! cross-linker

```

**Comment by andrewrobertjones** [comment]
Proposal seems reasonable, @germa  and @lutzfischer - please continue to work on this

Need to add lines to mapping file for linking to Unimod for regular mods and to XLMOD for these, so need appropriate branch node to link to. thanks Andy

**Comment by germa** [comment]
- Finished initial restructured version of XLMOD.obo
- requested to include XLMOD.obo in OBOFoundry.github.io
  (see pull request https://github.com/OBOFoundry/OBOFoundry.github.io/pull/284)
- TODO: Include XLMOD.obo into the EBI Open Lookup Service

**Comment by germa** [comment]
Had to change the identifiers from XL:nnnnn to XLMOD:nnnnn in order to avaoid name clashes, as reported by Chris Mungall, see https://github.com/OBOFoundry/OBOFoundry.github.io/pull/284

**Comment by edeutsch** [comment]
okay, fine. This means all the XL example files will need to be changed.

**Comment by andrewrobertjones** [comment]
@germa @edeutsch  Can we now close this thread? The new OBO looks sensible to me

**Comment by germa** [comment]
yes, the restructuring of xlmod.obo is finished
