### ISSUE TITLE
schemaLocations are highly variable

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#64]
What should the approved schemaLocation be? The various example files have many different ones:

mzidLib_peaklist2a_plus_ecoli_versus_unimod_full_xtandem_fdr_threshold_groups.mzid -  `xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.2 ../../../schema/mzIdentML1.2.0-candidate.xsd"`

OpenxQuest_example_added_annotations.mzid -     `xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.2.0 https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0.xsd"`

OpenxQuest_example.mzid -       
`xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.2.0 https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0.xsd"`

PeptideShaker_mzid_1_2_example.mzid - 
`<MzIdentML id="PeptideShaker v1.11.1-beta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.2 http://www.psidev.info/files/mzIdentML1.2.0.xsd" xmlns="http://psidev.info/psi/pi/mzIdentML/1.2" version="1.2.0" creationDate="2016-06-22T19:35:50">`

Maybe this latter one should be the recommended style?

Also, this one is still pointing to 1.1

mzidLib_Rosetta2a_Ecoli_spectra_msgfplus_fdr_threshold_groups.mzid - 
`<MzIdentML id="MS-GF+" version="1.2.0" xmlns="http://psidev.info/psi/pi/mzIdentML/1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.2 http://www.psidev.info/files/mzIdentML1.1.0.xsd" creationDate="2014-07-02T12:36:41" >`

**Comment by fghali** [comment]
I have update all mzidLib examples files to match PeptideShaker_mzid_1_2_example.mzid.

**Comment by mwalzer** [comment]
I also changed the schemalocations for QXQ (see also https://github.com/HUPO-PSI/mzIdentML/issues/52#issuecomment-228067679)

**Comment by edeutsch** [comment]
Is QXQ OpenXQuest? (OXQ?) Anyway, most files now seem fixed except the OpenxQuest files:

OpenxQuest_example_added_annotations.mzid -     xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.2.0 https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0.xsd"

OpenxQuest_example.mzid -       xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.2.0 https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0.xsd"

**Comment by mwalzer** [comment]
Yes, sorry I abbreviated OpenXQuest with QXQ.
I think these relate to files prior to PR https://github.com/HUPO-PSI/mzIdentML/pull/66

Easy access to the files from the PR here:
https://github.com/HUPO-PSI/mzIdentML/issues/52#issuecomment-230726074

**Comment by andrewrobertjones** [comment]
Hi all,
The style "http://www.psidev.info/files/mzIdentML1.2.0.xsd" would be perfectly good if the schema was actually there :-) Schema validators should be able to reach the file via the URL!

These URLs are also bad: https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0.xsd 

For now, can everyone @fghali  @mwalzer  @hbarsnes @mwalzer @smdb21  point their example files here: 

https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0-candidate.xsd

So that URL-enabled schema validators can pick these up. We can then fix these post-release.

**Comment by edeutsch** [comment]
Why not just actually put the current schema at  "http://www.psidev.info/files/mzIdentML1.2.0.xsd" ?

**Comment by andrewrobertjones** [comment]
@edeutsch I don't have a strong preference against moving the schema there, although I slightly prefer to wait until version 1.2 is signed off and released to avoid keeping this version and the GitHub version synced, unless there is a way for this to be done automatically. 
Hopefully there will be very few if any changes to the file now anyway, although during the doc proc, some issues in documentation might be identified.

**Comment by edeutsch** [comment]
okay.
