### ISSUE TITLE
potential data duplication enticement (1.2)

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzIdentML#65]
It seems to me as a potential point of confusion between 
```SpectrumIdentification ... activityDate=``` and *Rule ID: SpectrumIdentificationList_may_rule* 

(which recommends children of search statistics as cv elements in SIL {of which there are btw only 3: date / time search performed, search time taken, number of molecular hypothesis considered} )

**Comment by andrewrobertjones** [comment]
I think this is okay, the term definition makes it clear that it is obsolete:

[Term]
id: MS:1001035
name: date / time search performed
def: "OBSOLETE: use attribute in mzIdentML instead. Date and time of the actual search run." [PSI:PI]
is_a: MS:1001184 ! search statistics
is_obsolete: true
