### ISSUE TITLE
Remove the value requirement for CV terms used to indicate data type for a list

### ISSUE THREAD

**Issue by hbarsnes** [HUPO-PSI/mzIdentML#7]
At the meeting we agreed to remove the value requirement from the following MS:1001221 (fragmentation information) child terms:
   - MS:1001226 (product ion intensity)
   - MS:1002225 (average product ion intensity)
   - MS:1002226 (product ion intensity standard deviation)
   - MS:1000904 (product ion m/z delta)

The reason being that these terms are used as to describe the data type in mzid files as part of the FragmentationTable element and can thus have no value in this setup.

**Comment by germa** [comment]
Done in version 3.86.0 of psi-ms.obo
