### ISSUE TITLE
Validator issue due to lack of protein description lines

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzIdentML#71]
In multi_search/combined_1.2.mzid, we get validatior errors due to missing protein descriptions caused by this rule:

Message 339:
    Rule ID: DBSequence_ProteinDescription_must_rule
    Level: ERROR
    Context(/cvParam/@accession ) in 4881 locations
    --> None of the given CvTerms were found at '/MzIdentML/SequenceCollection/DBSequence/cvParam/@accession' because no values were found:
  - The sole term MS:1001088 (protein description) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name. 

@germa  I don’t recall the history of this MUST rule. I assume it is an error – we never before enforced DBSequence to have a protein description line, did this sneak in from MIAPE Validation perhaps? If so, can we change this to a MAY rule

**Comment by germa** [comment]
changed it to a may rule
