### ISSUE TITLE
Spectral library and de novo sequencing

### ISSUE THREAD

**Issue by andrewrobertjones** [HUPO-PSI/mzIdentML#72]
We have a minor error in the mapping file and docs, with regards to where terms should be used for spectral library search or de novo.

They should go in here instead of ms-ms search, and this is allowed according to the mapping file:
`    <SearchType>
      <cvParam cvRef="PSI-MS" accession="MS:1001083" name="ms-ms search"></cvParam>
    </SearchType>`

However, they are also allowed as AdditionalSearchParams, as per this rule :

`<CvMappingRule id="AdditionalSearchParams" cvElementPath="/MzIdentML/AnalysisProtocolCollection/SpectrumIdentificationProtocol/additionalSearchParams/cvParam/@accession" requirementLevel="MAY" scopePath="/MzIdentML/AnalysisProtocolCollection/SpectrumIdentificationProtocol/additionalSearchParams" cvTermsCombinationLogic="OR">
			...
            <CvTerm termAccession="MS:1001010" useTermName="false" useTerm="true" termName="de novo search" isRepeatable="false" allowChildren="false" cvIdentifierRef="MS" />
            <CvTerm termAccession="MS:1001031" useTermName="false" useTerm="true" termName="spectral library search" isRepeatable="false" allowChildren="false" cvIdentifierRef="MS" />`

The inclusion of these terms is supposed to trigger special behaviour in the validator (not checked yet), to allow for peptideEvidence to be zero to many cardinality. 

I think the correct fix is to just remove the mapping for these terms under AdditionalSearchParams, and make sure the validator picks up these terms for the special behaviour from SearchType. 

@germa  Can you action this, and I will action the change in the spec doc

**Comment by andrewrobertjones** [comment]
Further note - I just tried adding spectral library or de novo search terms to either or both of SearchType and AdditionalSearchParams, and in both cases I get an error if there are zero PeptideEvidences, so it looks like this rule has not been implemented yet.
@germa Please can you add this check so that if either term is present under SearchType, zero peptideEvidence is allowed. 

thanks

**Comment by germa** [comment]
term is now present under SearchType, zero peptideEvidence is allowed for de novo

**Comment by andrewrobertjones** [comment]
@germa Can you also confirm that zero peptideEvidence is allowed for spectral library searches as well, where spectral library search is a valid term under SearchType?

thanks, Andy

**Comment by germa** [comment]
yes, also spectral library search (with zero peptideEvidence) is now allowed under SearchType.
