### ISSUE TITLE
Validator question on the <schema> Element in <MzIdentML>

### ISSUE THREAD

**Issue by mwalzer** [HUPO-PSI/mzIdentML#79]
Validator gives 
```
Warning message: SchemaLocation: schemaLocation value = 'https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0-candidate.xsd' must have even number of URI's.
```
if ```<schema>``` Element in ```<MzIdentML>``` used minimalistic:
```
xmlns="http://psidev.info/psi/pi/mzIdentML/1.2"
xsi:schemaLocation="https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0-candidate.xsd"
```
So: Is it invalid to omit the namespace if default xmlns is given anyway?

Also, validator stops with 
```Exception in thread "Thread-2" java.lang.NullPointerException``` when ```version="1.2.0-candidate"```

**Comment by germa** [comment]
Because in mzIdentML1.2.0-candidate.xsd it's defined as targetNamespace="http://psidev.info/psi/pi/mzIdentML/1.2",
you must use that as first part of your schemaLocation:

xsi:schemaLocation="http://psidev.info/psi/pi/mzIdentML/1.2 https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/schema/mzIdentML1.2.0-candidate.xsd"

**Comment by mwalzer** [comment]
Yes, but if I define the default namespace of the xml like in the example above, I have already (the only) valid namespace. At least I could'nt find anything reading the W3C recommendations or W3schools, so I am curious.

**Comment by mwalzer** [comment]
mh, partially selfanswering: [from here](https://www.w3.org/TR/xmlschema-1/#xsi.schemaLocation)
{target namespace}	The ·actual value· of the targetNamespace [attribute] of the parent <schema> element information item, or ·absent· if there is none.

seems to imply that it is no namespace definition for the XML but a reiteration of the referenced schema namespace.
