### ISSUE TITLE
Validation issues with DTASelect-filter.mzid

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#82]
ERROR: cvParam family member protein should have a value, but it does not!

ERROR: cvParam normalized spectral abundance factor has a value, but it should not!

ERROR: cvParam PAnalyzer:ambiguous group member should have a value, but it does not!

ERROR: cvParam PAnalyzer:conclusive protein should have a value, but it does not!

ERROR: cvParam PAnalyzer:indistinguishable protein should have a value, but it does not!

ERROR: cvParam PAnalyzer:non-conclusive protein should have a value, but it does not!

ERROR: cvParam protein description should have a value, but it does not!

ERROR: cvParam sample pre-fractionation has a value, but it should not!

ERROR: cvParam scan start time should have units, but it does not!

ERROR: cvParam sequence same-set protein should have a value, but it does not!

ERROR: cvParam sequence sub-set protein should have a value, but it does not!

ERROR: cvParam software vendor has a value, but it should not!

WARNING: MS:1001448 should be 'pep:FDR threshold' instead of 'Pep:FDR threshold'

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264845, char 148

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value 'C:\Users\Salva\Desktop\tmp\dtaselect2mzid\SILAC example\DTASelect-filter.txt' is NOT a valid U

RI .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264862, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-12.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264871, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-01.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264880, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-10.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264889, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-02.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264898, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-11.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264907, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-03.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264916, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-04.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264925, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-05.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264934, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-06.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264943, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-07.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264952, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-08.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264961, char 132

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\silam-fmrKO1P17-ctx-p2-09.ms2' is NOT a valid URI 

.

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264970, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-12.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264979, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-10.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264988, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-11.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 264997, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-04.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 265006, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-03.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 265015, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-06.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 265024, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-05.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 265033, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-02.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 265042, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-01.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 265051, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-09.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 265060, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-08.ms2' is NOT a valid URI

 .

Error at file /net/db/projects/PSI/mzIdentML/1.2/genDoc/DTASelect-filter.mzid, line 265069, char 134

  Message: Datatype error: Type:InvalidDatatypeValueException, Message:Value '/ddn/people/lliao/projects2010_09_01_145478\Hsilam-fmrKO1P17-ctx-p2-07.ms2' is NOT a valid URI

 .

**Comment by smdb21** [comment]
Hi Eric! I just see this here in the issue list that was posted long time ago.
I just run the latest version with this file and I am getting other errors:
```
The following messages were obtained during the validation of your XML file:


Message 1:
    Rule ID: ProteinDetectionList_must_rule
    Level: ERROR
    Context(/cvParam/@accession ) in 2 locations
    --> None of the given CvTerms were found at '/MzIdentML/DataCollection/AnalysisData/ProteinDetectionList/cvParam/@accession' because no values were found:
  - The sole term MS:1002404 (count of identified proteins) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.


Message 2:
    Rule ID: ProteinDetectionList_may_rule
    Level: INFO
    Context(/cvParam/@accession ) in 2 locations
    --> None of the given CvTerms were found at '/MzIdentML/DataCollection/AnalysisData/ProteinDetectionList/cvParam/@accession' because no values were found:
  - Any children term of MS:1001184 (search statistics). The term can be repeated. The matching value has to be the identifier of the term, not its name.
  - Any children term of MS:1002405 (protein group-level result list attribute). A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - Any children term of MS:1002704 (protein-level result list attribute). A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.


Message 3:
    Rule ID: SpectrumIdentificationList_may_rule
    Level: INFO
    Context(/cvParam/@accession ) in 25 locations
    --> None of the given CvTerms were found at '/MzIdentML/DataCollection/AnalysisData/SpectrumIdentificationList/cvParam/@accession' because no values were found:
  - Any children term of MS:1001184 (search statistics). The term can be repeated. The matching value has to be the identifier of the term, not its name.


Message 4:
    Rule ID: MassTable_may_rule
    Level: INFO
    Context(/massTable/cvParam/@accession ) in 3 locations
    --> None of the given CvTerms were found at '/MzIdentML/AnalysisProtocolCollection/SpectrumIdentificationProtocol/massTable/cvParam/@accession' because no values were found:
  - Any children term of MS:1001354 (mass table options). The term can be repeated. The matching value has to be the identifier of the term, not its name.


======== RULE STATISTICS ========
Invalid XML schema validation: 0

CvMappingRule total count: 50
CvMappingRules not run: 2
CvMappingRules run & invalid: 4
CvMappingRules invalid XPath: 0
CvMappingRules run & valid: 44

ObjectRules total count: 15
ObjectRules not run: 2
ObjectRules run & not matching: 0
ObjectRules run & valid: 13

Unanticipated CV terms: 0
Not matching messages received: 4
```
Do you still want me to fix this? 
It seems that we still have some issues that are not solved related to the example files.

**Comment by edeutsch** [comment]
Yes, please do fix. Although I haven't looked carefully enough, you should double check to make sure that the file is indeed incorrect. It is always possible that the file is correct but the validator (or mapping file) is wrong.

thanks!
Eric

**Comment by ypriverol** [comment]
This is an old issue. Unless @edeutsch you have major complains I will close it.
