### ISSUE TITLE
Validation issues with xiFDR-CrossLinkExample_single_run.mzid

### ISSUE THREAD

**Issue by edeutsch** [HUPO-PSI/mzIdentML#84]
ERROR: cvParam anchor protein should have a value, but it does not!

WARNING: MS:1000563 should be 'Thermo RAW format' instead of 'Thermo Raw file'

WARNING: MS:1002404 should be 'count of identified proteins' instead of 'count of identified protein'

WARNING: MS:1002511 should be 'cross-link spectrum identification item' instead of 'Cross-linked spectrum identification item.'

WARNING: MS:1002544 should be 'xi' instead of 'xiFDR'

WARNING: MS:1002545 should be 'xi:score' instead of 'The xi result 'Score'.'

**Comment by lutzfischer** [comment]
should be fixed now
I replaced "anchor protein" by "group representative" and corrected the names of the other ones

**Comment by edeutsch** [comment]
This one is still there..

INFO: Validating file 'xiFDR-CrossLinkExample_single_run.mzid'
WARNING: MS:1002511 should be 'cross-link spectrum identification item' instead of 'cross-linked spectrum identification item'

**Comment by lutzfischer** [comment]
new version of the xiFDR examples that have 'cross-link spectrum identification item' instead of 'cross-linked spectrum identification item'
