### ISSUE TITLE
Modification Scores encode in mzIDentML

### ISSUE THREAD

**Issue by ypriverol** [HUPO-PSI/mzIdentML#86]
@andrewrobertjones can you point to the place that explain how we are encoding PTMs in localization score in mzIdentML?

**Comment by andrewrobertjones** [comment]
Yup - Specification document for 1.2-release section 5.2.8

**Comment by ypriverol** [comment]
Great, we have a couple of examples already in PRIDE that represents in mzIdentML 1.1 like: 

<SpectrumIdentificationItem passThreshold="true" rank="1" peptide_ref="Pep17" calculatedMassToCharge="717.5849609375" experimentalMassToCharge="717.8302001953125" chargeState="4" id="SII_20_1">
      <PeptideEvidenceRef peptideEvidence_ref="PepEv_262235_17_1"></PeptideEvidenceRef>
      <cvParam accession="MS:1002049" cvRef="PSI-MS" value="24" name="MS-GF:RawScore"></cvParam>
      <cvParam accession="MS:1002050" cvRef="PSI-MS" value="127" name="MS-GF:DeNovoScore"></cvParam>
      <cvParam accession="MS:1002052" cvRef="PSI-MS" value="1.155511E-5" name="MS-GF:SpecEValue"></cvParam>
      <cvParam accession="MS:1002053" cvRef="PSI-MS" value="253.293" name="MS-GF:EValue"></cvParam>
      <cvParam accession="MS:1002054" cvRef="PSI-MS" value="0.24" name="MS-GF:QValue"></cvParam>
      <cvParam accession="MS:1002055" cvRef="PSI-MS" value="0.30769232" name="MS-GF:PepQValue"></cvParam>
      <userParam value="1" name="IsotopeError"></userParam>
      <userParam value="ETD" name="AssumedDissociationMethod"></userParam>
      <userParam value="0.62728024" name="ExplainedIonCurrentRatio"></userParam>
      <userParam value="0.37976825" name="NTermIonCurrentRatio"></userParam>
      <userParam value="0.24751195" name="CTermIonCurrentRatio"></userParam>
      <userParam value="13405.929" name="MS2IonCurrent"></userParam>
      <userParam value="9" name="NumMatchedMainIons"></userParam>
      <userParam value="162.07416" name="MeanErrorAll"></userParam>
      <userParam value="83.3318" name="StdevErrorAll"></userParam>
      <userParam value="174.7711" name="MeanErrorTop7"></userParam>
      <userParam value="76.8809" name="StdevErrorTop7"></userParam>
      <userParam value="25.175926" name="MeanRelErrorAll"></userParam>
      <userParam value="180.49486" name="StdevRelErrorAll"></userParam>
      <userParam value="-1.2409058" name="MeanRelErrorTop7"></userParam>
      <userParam value="190.92949" name="StdevRelErrorTop7"></userParam>
      <cvParam accession="MS:1001969" cvRef="PSI-MS" value="51.338711182474654" name="ProteomeDiscoverer:phosphoRS score"></cvParam>
      <cvParam accession="MS:1001970" cvRef="PSI-MS" value="0.44174725282002375" name="ProteomeDiscoverer:phosphoRS sequence probability"></cvParam>
      <cvParam accession="MS:1001971" cvRef="PSI-MS" value="S(5): 0.1; T(11): 44.2; S(12): 5.7; T(16): 5.7; T(17): 44.2; Y(24): 0.0" name="ProteomeDiscoverer:phosphoRS site probabilities"></cvParam>
    </SpectrumIdentificationItem>

Would be great for the possible exporters to 1.1 to know that mechanisms.
