### ISSUE TITLE
Link current specdoc 1.2 to the README

### ISSUE THREAD

**Issue by julianu** [HUPO-PSI/mzIdentML#88]
The specification document on the landing page is still linked to Version 1.1.0
1.2.0 is now published and passed the spec-doc (right?), so should be linked here.

**Comment by mwalzer** [comment]
Right. In any case, the page looks presents like a wall of text, could be a serious case of TL;DR for new visitors.

**Comment by andrewrobertjones** [comment]
Do you mean on this page: http://www.psidev.info/proteomicsinformatics#mzIdentML?

Yes it needs updating, but my login doesn't seem to allow me to edit this page. @eisenachM  or @javizca  - Martin/Juan - can you fix this page?

**Comment by mwalzer** [comment]
@andrewrobertjones I think Julian is referring the [Readme.md](https://github.com/HUPO-PSI/mzIdentML/blob/master/README.md) but that one needs updating, too.

**Comment by andrewrobertjones** [comment]
Yes just spotted that, I will update the readme now

**Comment by andrewrobertjones** [comment]
Updated Readme, let me know if you spot other pages that need fixing

**Comment by julianu** [comment]
Jep, i meant the Readme.md
Thanks for fixing.
