### ISSUE TITLE
Exporting Crosslink Modifications

### ISSUE THREAD

**Issue by ciesinsk** [HUPO-PSI/mzIdentML#96]
Hi. 

I created an mzIdentML export that contains crosslinks. I get the following error in the validator: 

Message 1:
    Rule ID: PeptideModification_must_rule
    Level: ERROR
    Context(/modification/cvParam/@accession ) in 312 locations
    --> The result found at: /modification/cvParam/@accession for which the values is  ''XLMOD:02126'' didn't match any of the 7 specified CV terms:
  - The sole term MS:1002509 (cross-link donor) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - The sole term MS:1002510 (cross-link acceptor) or any of its children. A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - Any children term of UNIMOD:0 (unimod root node). A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - Any children term of MOD:00000 (protein modification). A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - Any children term of MS:1001471 (peptide modification details). A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - Any children term of XLMOD:00002 (cross-linker related PTM). A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.
  - Any children term of XLMOD:00004 (cross-linker). A single instance of this term can be specified. The matching value has to be the identifier of the term, not its name.

But the DSSO linker is defined correctly in the obo file: 

[Term]
id: XLMOD:00004
name: cross-linker
def: "Compound that can link two or more polymer chains." [PSI:XL]
is_a: XLMOD:00001 ! cross-linking entity

[Term]
id: XLMOD:00005
name: homofunctional cross-linker
def: "A cross-linking reagent with identical reactive groups at each end of the spacer arm." [PSI:XL]
is_a: XLMOD:00004 ! cross-linker

[Term]
id: XLMOD:02126
name: DSSO
def: "Disuccinimidyl sulfoxide." [PMID:20736410, PMID:27417384]
property_value: reactionSites: "2" xsd:nonNegativeInteger
property_value: spacerLength: "10.1" xsd:float
is_a: XLMOD:00005 ! homofunctional cross-linker
relationship: has_reactive_group XLMOD:00101 ! NHS ester
relationship: is_cleavable XLMOD:00067 ! CID cleavable C-S bond

An example excerpt from the actual mzIdentML file contains the following: 
/* Peptide in mzid file */

 <Peptide id="XL_-24_27_DON">
      <PeptideSequence>ENVIPADSEKK</PeptideSequence>
      <Modification monoisotopicMassDelta="158.00376" location="10">
        <cvParam accession="XLMOD:02126" cvRef="XLMOD" name="DSSO" />
      </Modification>
    </Peptide>
    <Peptide id="XL_-24_27_RCV">
      <PeptideSequence>DVEEKPAHAPARPEAPVDSMLK</PeptideSequence>
      <Modification monoisotopicMassDelta="15.994915" location="20">
        <cvParam accession="UNIMOD:35" cvRef="UNIMOD" name="Oxidation" />
      </Modification>
      <Modification monoisotopicMassDelta="0.0" location="5">
        <cvParam accession="XLMOD:02126" cvRef="XLMOD" name="DSSO" />
      </Modification>
</Peptide>

/* Reference definition in CVLIST */

  <cvList xmlns="http://psidev.info/psi/pi/mzIdentML/1.2">
    <cv id="PSI-MS" uri="http://psidev.cvs.sourceforge.net/viewvc/*checkout*/psidev/psi/psi-ms/mzML/controlledVocabulary/psi-ms.obo" version="3.70.1" fullName="Proteomics Standards Initiative Mass Spectrometry Ontology" />
    <cv id="XLMOD" uri="https://raw.githubusercontent.com/HUPO-PSI/mzIdentML/master/cv/XLMOD.obo" version="1.1.0" fullName="cross-linking reagents and cross-linker related post-translational modifications" />
    <cv id="UNIMOD" uri="http://www.unimod.org/obo/unimod.obo" fullName="UNIMOD" />
    <cv id="UO" uri="http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/phenotype/unit.obo" fullName="UNIT-ONTOLOGY" />
  </cvList>

As far as I can see I do everything correct. Maybe I am missing something obvious? 

Regards, Frank.

**Comment by andrewrobertjones** [comment]
Hi Frank, 

Thanks for reporting. @germa  would you mind investigating?
best wishes
Andy

**Comment by germa** [comment]
Hi Frank,

yes, should be ok.
Would it be possible that you send me the .mzid file for testing?

Regards,
Gerhard

**Comment by ciesinsk** [comment]
Hi Gerhard.

Thanks for the quick response! I would be glad if I could help in any way.
Please find attached the file you requested.
BTW: Issue #95 (Exception throws when launching version 1.4.27 of the
validator) also affects me. Maybe with the newer version my output
would already work?

Cheers, Frank.

**Comment by germa** [comment]
Hi Frank,

the version 1.4.28 should start now without the Exception.

If the validation of your .mzid file still reports the Error from violated PeptideModification_must_rule
then please send me the .mzid file (I think you forgot last time to attach it).

Best wishes,
Gerhard

**Comment by ciesinsk** [comment]
Hi Gerard.

Thanks, I will test it. :)

Cheers, Frank.

**Comment by colin-combe** [comment]
Seems like this could be closed?

**Comment by germa** [comment]
done.
