### ISSUE TITLE
Validator bugs on Peaks mzid file

### ISSUE THREAD

**Issue by UKQIDA** [HUPO-PSI/mzIdentML#97]
The second line of mzid file exported from Peaks Studio 8.0 is a comment read as:
.
However, the validator reports the file 'is not a mzIdentML file.‘ 
The logic of the codes lies in makeBasicXMLFileChecks(File xmlFile) function of MzIdentMLValidator.java.
It expects <MzIdentML at the second line of the file.
It would be easy to skip any comment line by conditional statement.

Thanks,
Da

**Comment by germa** [comment]
Solved in mzIdentMLValidator_GUI_v1.4.31-SNAPSHOT
