### ISSUE TITLE
Unanticipated CV terms from validator

### ISSUE THREAD

**Issue by UKQIDA** [HUPO-PSI/mzIdentML#98]
Hi Gerhard, 

When I run the validator on mzIdentML v1.2 files, the following warning messages were given:

> Message 1:
>     Level: WARN
>     --> unanticipated terms for XPath '/MzIdentML/SequenceCollection/DBSequence/cvParam/@accession' : [MS:1002644, MS:1002637, MS:1002638, MS:1002741]
> 
> 
> Message 2:
>     Level: WARN
>     --> unanticipated terms for XPath '/MzIdentML/AnalysisProtocolCollection/SpectrumIdentificationProtocol/additionalSearchParams/cvParam/@accession' : [MS:1002635]
> 
> 
> Message 3:
>     Level: WARN
>     --> unanticipated terms for XPath '/MzIdentML/AnalysisProtocolCollection/SpectrumIdentificationProtocol/modificationParams/searchModification/cvParam/@accession' : [MS:1001189]

I am pretty sure that those CV terms are correct defined in 1.2 specification document page 24 section "Guidelines for encoding proteogenomics results".  

Thanks,
Da

**Comment by germa** [comment]
Solved in mzIdentMLValidator_GUI_v1.4.31-SNAPSHOT
